version: '2'

services:

  bash:
    image: djangorestapi
    volumes:
      - .:/djangorestapi
    working_dir: /djangorestapi
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: bash
    
  migrate:
    extends:
      file: docker-compose.yml
      service: bash
    entrypoint: python manage.py migrate

  server:
    extends:
      file: docker-compose.yml
      service: bash
    ports:
      - "8000:8000"
    entrypoint: python manage.py runserver 0.0.0.0:8000

